
// This file has been generated by the GUI designer. Do not modify.
namespace CGtk
{
	public partial class Cayegoria
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Table table1;

		private global::Gtk.Label label1;

		private global::Gtk.Entry Nombre;

		private global::Gtk.HButtonBox hbuttonbox5;

		private global::Gtk.Button button5;

		private global::Gtk.Button button6;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CGtk.Cayegoria
			this.Name = "CGtk.Cayegoria";
			this.Title = global::Mono.Unix.Catalog.GetString("Cayegoria");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child CGtk.Cayegoria.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.Nombre = new global::Gtk.Entry();
			this.Nombre.CanFocus = true;
			this.Nombre.Name = "Nombre";
			this.Nombre.IsEditable = true;
			this.Nombre.InvisibleChar = '•';
			this.table1.Add(this.Nombre);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.Nombre]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add(this.table1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox5 = new global::Gtk.HButtonBox();
			this.hbuttonbox5.Name = "hbuttonbox5";
			// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
			this.button5 = new global::Gtk.Button();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("_Cancelar");
			global::Gtk.Image w4 = new global::Gtk.Image();
			this.button5.Image = w4;
			this.hbuttonbox5.Add(this.button5);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.button5]));
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
			this.button6 = new global::Gtk.Button();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseStock = true;
			this.button6.UseUnderline = true;
			this.button6.Label = "gtk-ok";
			this.hbuttonbox5.Add(this.button6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.button6]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox2.Add(this.hbuttonbox5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox5]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 140;
			this.Show();
		}
	}
}
